import { workflow, node, trigger, ifElse, merge, expr } from '@n8n/workflow-sdk';
const T = (id: string) => ({ __rl: true, mode: 'name', value: id });
const manual = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Manual' }, output: [{}] });
const seed = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Seed', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: 'return [{ json: { n: 1 } }];' } }, output: [{ n: 1 }] });
const cond = ifElse({ version: 2.2, config: { name: 'Always False', parameters: { conditions: { options: { caseSensitive: true, leftValue: '', typeValidation: 'strict', version: 2 }, conditions: [{ leftValue: expr('{{ String($json.n) }}'), operator: { type: 'string', operation: 'equals' }, rightValue: 'zzz' }], combinator: 'and' } } } });
const mrg = merge({ version: 3.2, config: { name: 'Merge Probe', parameters: { mode: 'append', numberInputs: 2 } } });
const mergeCheck = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Merge Check', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: 'return [{ json: { merge_items: $input.all().length, first: $input.first() ? $input.first().json : null } }];' } }, output: [{ merge_items: 1 }] });
const cols = ['state_key','code','severity','subject','status','first_seen','last_seen','last_alerted','times_alerted','detail'];
const sch = cols.map((c) => ({ id: c, displayName: c, required: false, defaultMatch: false, display: true, type: c === 'times_alerted' ? 'number' : 'string', canBeUsedToMatch: c === 'state_key' }));
const val: any = {}; cols.forEach((c) => { val[c] = c === 'state_key' ? '__PROBE__' : c === 'times_alerted' ? expr('{{ $runIndex + 1 }}') : 'probe'; });
const mkUp = (name: string) => node({ type: 'n8n-nodes-base.dataTable', version: 1.1, config: { name, parameters: { resource: 'row', operation: 'upsert', dataTableId: T('mtg_monitor_state'), matchType: 'allConditions', filters: { conditions: [{ keyName: 'state_key', condition: 'eq', keyValue: '__PROBE__' }] }, columns: { mappingMode: 'defineBelow', value: val, schema: sch } }, executeOnce: true }, output: [{ id: 1 }] });
const up1 = mkUp('Upsert 1'); const up2 = mkUp('Upsert 2');
const getP = node({ type: 'n8n-nodes-base.dataTable', version: 1.1, config: { name: 'Get Probe', parameters: { resource: 'row', operation: 'get', dataTableId: T('mtg_monitor_state'), matchType: 'allConditions', filters: { conditions: [{ keyName: 'state_key', condition: 'eq', keyValue: '__PROBE__' }] }, returnAll: true }, alwaysOutputData: true, executeOnce: true }, output: [{ id: 1 }] });
const delP = node({ type: 'n8n-nodes-base.dataTable', version: 1.1, config: { name: 'Delete Probe', parameters: { resource: 'row', operation: 'deleteRows', dataTableId: T('mtg_monitor_state'), matchType: 'allConditions', filters: { conditions: [{ keyName: 'state_key', condition: 'eq', keyValue: '__PROBE__' }] } }, executeOnce: true }, output: [{ id: 1 }] });
const getA = node({ type: 'n8n-nodes-base.dataTable', version: 1.1, config: { name: 'Get After Delete', parameters: { resource: 'row', operation: 'get', dataTableId: T('mtg_monitor_state'), matchType: 'allConditions', filters: { conditions: [{ keyName: 'state_key', condition: 'eq', keyValue: '__PROBE__' }] }, returnAll: true }, alwaysOutputData: true, executeOnce: true }, output: [{ id: 1 }] });
const getO = node({ type: 'n8n-nodes-base.dataTable', version: 1.1, config: { name: 'Get Ordered', parameters: { resource: 'row', operation: 'get', dataTableId: T('mtg_job_scout_run_log'), returnAll: false, limit: 6, orderBy: true, orderByColumn: 'started_at', orderByDirection: 'DESC' }, alwaysOutputData: true, executeOnce: true }, output: [{ id: 1 }] });
const getAll = node({ type: 'n8n-nodes-base.dataTable', version: 1.1, config: { name: 'Get Empty Table', parameters: { resource: 'row', operation: 'get', dataTableId: T('mtg_monitor_run_log'), returnAll: true }, alwaysOutputData: true, executeOnce: true }, output: [{ id: 1 }] });
const nc = { notionApi: { id: 'dmZi56n3pGMhm5Xe', name: 'Notion account' } };
const hdr = { parameters: [{ name: 'Notion-Version', value: '2025-09-03' }] };
const schema = node({ type: 'n8n-nodes-base.httpRequest', version: 4.3, config: { name: 'Lead Schema', parameters: { method: 'GET', url: 'https://api.notion.com/v1/data_sources/05a640fc-dff7-4975-9b85-e818008c642e', authentication: 'predefinedCredentialType', nodeCredentialType: 'notionApi', sendHeaders: true, headerParameters: hdr, options: {} }, credentials: nc, onError: 'continueRegularOutput', executeOnce: true }, output: [{ properties: {} }] });
const buildQ = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Build Q', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: "const A=['Lead ID','Lead Status','Status Changed','Last Contact','Purge After','PII Purged','Human Action','Draft Kind'];const p=($input.first().json||{}).properties||{};const ids=[],miss=[];A.forEach(n=>{if(p[n]&&p[n].id)ids.push(p[n].id);else miss.push(n);});return [{json:{ok:!miss.length,miss,ids,url:'https://api.notion.com/v1/data_sources/05a640fc-dff7-4975-9b85-e818008c642e/query?'+ids.map(i=>'filter_properties='+encodeURIComponent(i)).join('&'),schemaObject:($input.first().json||{}).object||null}}];" } }, output: [{ ok: true }] });
const leadQ = node({ type: 'n8n-nodes-base.httpRequest', version: 4.3, config: { name: 'Lead Query', parameters: { method: 'POST', url: expr('{{ $json.url }}'), authentication: 'predefinedCredentialType', nodeCredentialType: 'notionApi', sendHeaders: true, headerParameters: hdr, sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: '={{ JSON.stringify({ page_size: 100, sorts: [{ timestamp: "last_edited_time", direction: "descending" }] }) }}', options: {} }, credentials: nc, onError: 'continueRegularOutput', executeOnce: true }, output: [{ results: [] }] });
const masterQ = node({ type: 'n8n-nodes-base.httpRequest', version: 4.3, config: { name: 'Master UniqueId Query', parameters: { method: 'POST', url: 'https://api.notion.com/v1/data_sources/a5cfe2a2-de3f-426c-8449-77f0de1c24c9/query', authentication: 'predefinedCredentialType', nodeCredentialType: 'notionApi', sendHeaders: true, headerParameters: hdr, sendBody: true, contentType: 'json', specifyBody: 'json', jsonBody: '={{ JSON.stringify({ filter: { property: "Job ID", unique_id: { equals: 1 } }, page_size: 1, filter_properties: ["title"] }) }}', options: {} }, credentials: nc, onError: 'continueRegularOutput', executeOnce: true }, output: [{ results: [] }] });
const report = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Report', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: `const c=(n)=>{try{return $(n).all().map(i=>i.json);}catch(e){return 'ERR '+e.message;}};
const lq=c('Lead Query')[0]||{}; const bq=c('Build Q')[0]||{}; const mq=c('Master UniqueId Query')[0]||{};
const gp=c('Get Probe'), ga=c('Get After Delete'), go=c('Get Ordered'), ge=c('Get Empty Table');
return [{json:{
 merge: c('Merge Check'),
 upsert_probe_rows_after_2_upserts: gp.length, probe_row: gp[0]||null,
 after_delete_items: ga.length, after_delete_first_keys: ga[0]?Object.keys(ga[0]):null,
 ordered_items: go.length, ordered_first: go[0]||null,
 empty_table_items: ge.length, empty_first: ge[0]||null,
 lead_schema_ok: bq.ok, lead_missing: bq.miss, lead_ids: bq.ids&&bq.ids.length, schema_object: bq.schemaObject,
 lead_query_object: lq.object, lead_query_err: lq.message||lq.code||null, lead_results: Array.isArray(lq.results)?lq.results.length:null,
 lead_first_prop_keys: Array.isArray(lq.results)&&lq.results[0]?Object.keys(lq.results[0].properties):null,
 master_object: mq.object, master_err: mq.message||mq.code||null, master_results: Array.isArray(mq.results)?mq.results.length:null
}}];` } }, output: [{}] });
export default workflow('mtg-probe', 'MTG Phase A Contract Probe')
  .add(manual).to(seed).to(cond.onTrue(mrg.input(0)).onFalse(mrg.input(1)))
  .add(mrg).to(mergeCheck).to(up1).to(up2).to(getP).to(delP).to(getA).to(getO).to(getAll).to(schema).to(buildQ).to(leadQ).to(masterQ).to(report);
